title: Anubhav Singh
logo: "/profile_pic.jpg"
description: >
  <br>
  Frontend Engineer | Python Developer | SQL developer
  <br>
  <a href="https://www.linkedin.com/in/anubhav-solanki2911/">
    <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="mailto:anubhavsingh.28943@gmail.com">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>
theme: jekyll-theme-minimal
